name: 'Rust Checks'
description: 'Run various rust checks'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Run Rust checks
      shell: bash
      run: |
        cargo fmt --check
        cargo check
        cargo check --tests
        cargo clippy -- -D warnings
        cargo test --all
