runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    # TODO: this has been archived
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, clippy

    - shell: bash
      run: |
        cargo install just
        just init
        cargo fmt --check
        cargo check
        cargo check --tests
        cargo clippy -- -D warnings
        cargo test --all
