name: 'Rust Checks'
description: 'Run various rust checks'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, clippy

    - shell: bash
      run: cargo fmt --check

    - shell: bash
      run: cargo check

    - shell: bash
      run: cargo check --tests

    - shell: bash
      run: cargo clippy -- -D warnings

    - shell: bash
      run: cargo test --all
